server:
  port: 10001
  servlet:
    session:
      timeout: 30m

spring:
  application:
    name: gulimall-product
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.211.132:3306/gulimall_pms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.jdbc.Driver

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  redis:
    host: 192.168.211.132
    port: 6379
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

#开启feign对sentinel的支持
feign:
  sentinel:
    enabled: true

    #关闭thymeleaf缓存
  thymeleaf:
    cache: false

  session:
    store-type: redis

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml

  #设置实体类的自增主键
  global-config:
    db-config:
      id-type: auto
      #逻辑删除
      logic-delete-value: 1
      logic-not-delete-value: 0

logging:
  level:
    com.xunqi.gulimall: info
    com:
      alibaba:
        nacos:
          client:
            naming=warn:
#暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: '*'